### ISSUE TITLE
Merge in Chunk w/ Accents

### ISSUE THREAD

**Issue by micahbrich** [theleagueof/chunk#1]
We found someone who had extended Chunk with a bunch of extra accents, and we'd like to check it out and possibly merge in the changes!

http://svay.com/blog/index/post/2010/05/16/Chunk-font,-now-with-accents

**Comment by JtLively** [comment]
Page inactive.

**Comment by sursly** [comment]
Working on this right now. Drew em from scratch

**Comment by sursly** [comment]
Think we're good here.
